### ISSUE TITLE
tdCardNumber is too larger and causes 'Prefill' to be out-of-the-screen

### ISSUE THREAD

**Issue by Kwok-he-Chu** [adyen-examples/adyen-testcards-extension#20]
Prefill is out-of-the-screen when a card is favorited (unless expanded).

When favoriting a card, the card number (such as 222 4000 7000 0005) is not collapsed compared to: 3700 0000 0000 002

<img width="397" alt="image" src="https://github.com/adyen-examples/adyen-testcards-extension/assets/105217051/2bed2559-7a02-4102-a5b5-d1301129fd48">

**Suggested changes**
- Fix the css tdCardNumber class in `<td class="tdCardNumber">2222 4000 7000 0005</td>`
- Turn "copy" into the "copy"-image as we know we save space

**Comment by gcatanese** [comment]
@Kwok-he-Chu The issue is caused by long GiftCard numbers that do not contain spaces (unlike cards) and they don't wrap. Reducing the font size #27 has addressed this.
