### ISSUE TITLE
Favourited cards do not show expiration date and cvc

### ISSUE THREAD

**Issue by mglavall** [adyen-examples/adyen-testcards-extension#22]
Hello,

First of all, thanks for the extension. I use it everyday and helps me a lot.

This issue is about the favourite feature. I do not have the adyen drop-in payment flow so I do not benefit from the `Prefill` button, so I manually copy the card number, cvc and expiration date to test my checkout. I currently can not use favourites because when I do the cvc and expiration date are replaced by the brand logo, so I have no way of copying the CVC and EXP date. 

**My suggestion**: Keep the CVC and expiration date and make it so when you click at the field you copy the value. You can still keep the brand logo at the end of everything maybe.
I will be happy to submit a PR if you like this idea, let me know :)

Thanks again.

**Comment by gcatanese** [comment]
Hello @mglavall, thank you very much for the great feedback and the suggestions, we appreciate your help to make the extension better.
On principle submitting a PR would be great, but the extension is still in an early phase and we are already working on some changes, I hope we can soon have a stable version and accept your contributions.

Nevertheless your suggestions are great and we want to take them on board ASAP:
- show CVC and date in the Favourites
- also allow copy (in the clipboard) of each field when clicking on it (in this case you would copy each field just with a click and paste it where you need it)

We are already working on it! Please reach out if you have more feedback and suggestion.

**Comment by gcatanese** [comment]
@mglavall we have implemented this, still to reviewed/finalised but it would be great if you can check the [branch](https://github.com/adyen-examples/adyen-testcards-extension/tree/22-copy-on-click) and load the extension from the source code
