### ISSUE TITLE
Extend Prefill functionality

### ISSUE THREAD

**Issue by Kwok-he-Chu** [adyen-examples/adyen-testcards-extension#5]
Pressing the "Prefill" functionality should override & copy-paste the test card number into the Dropin/component.

This also covers the scenario in the case of clicking on the wrong card while prefilling.

**Comment by gcatanese** [comment]
@Kwok-he-Chu This seems to work in the latest version, please verify.

**Comment by Kwok-he-Chu** [comment]
Verified, prefilling works. Closing this issue.
